// Next.js file templates
const jsxPageTemplate = () => `
import React from 'react';

export default function Page() {
    return (
        <div>
            <h1>Page</h1>
            <p>This is a new page generated by your CLI.</p>
        </div>
    )    
}
`;

const tsxPageTemplate = () => `
import React from 'react';

export default function Page() {
  return (
    <div>
      <h1>Page</h1>
      <p>This is a new page generated by your CLI.</p>
    </div>
  );
};
`;

module.exports = { jsxPageTemplate, tsxPageTemplate };
